### PR TITLE
Add bootstrap error analysis to 3Drelocate

### PR DESCRIPTION
**Pull request by malcolmw**

### CODE REVIEW

**Comment by decibelhertz** [comment]
Thanks for the well-organized PR.

**Comment by malcolmw** [comment]
I got myself into a bit of a tangle and may have included a few unnecessary merges.

**Comment by decibelhertz** [comment]
These things happen. In all, the commits are easy to follow; I did mean it as compliment.

To avoid weird merges in the future, you can start afresh with your master branch, only ever pulling from this repo for master-->master pulls.  Then, your topic branches will not conflict as much.  You can also try a `git pull --rebase <aug_reponame>` instead of a merge; that will replay your changes atop this repo.

**Comment by malcolmw** [comment]
I didn't interpret it otherwise, just fishing for the advice you just provided. Thanks!

**Pull request merged**
