### PR TITLE
Support writing multiple events

### PR DESCRIPTION
**Pull request by nackerley**
As the title of the pull request suggests, the main focus here was adding support for writing of multiple events into one QuakeML file, but there are many other improvements, including:

- added support for 2-letter event type and certainty coding as per Storchak et al. (2012)
- added support for amplitudes 
- implemented an algorithm for selecting preferred magnitude
- added parsing parsing of origin.depth_type
- incorporated antelope version (from environment) and module name (from author) in methodID. 
- upgraded dict to OrderedDict so XML is ordered largely as per Schorlemmer et al. (2013)
- enforced PEP8 compliance
- streamlined logging 
- implemented an installer using setuptools

Unfortunately there is no unittest implemented for this module, so I can't guarantee that I haven't broken some use case for someone else. In fact it's likely that I have.

### CODE REVIEW

**Comment by nackerley** [comment]
Is there a way to ensure that this PR gets reviewed by some of the known end users?

**Comment by geoffdavis** [comment]
Hi Nick,

Thanks for the contribution! In terms of review by end users, we don’t really have a formalized process for that. I imagine though that anyone who’s interested will contact you if they run into problems running the code, assuming you added yourself to the author list.

If you’d be so kind, it’d be awesome if you could add some unit tests for the functions you added. Testing is something that historically hasn’t been well codified, so examples in the antelope_contrib repository would be of benefit to everyone as well.

**Comment by nackerley** [comment]
hi Geoff,

Thanks for looking at this.

I have to confess. I haven't been using event2qml.py. When I started at this the parameter file configuration system seemed overkill, especially considering event2qml was only capable of processing one event at a time. Thus it is quite possible that in this PR event2qml is broken. It would be helpful for me to understand more about who uses event2qml, and for what. 

On the other hand, I have written tests for a command-line tool which lets you subset the origin table from and exercises export_events pretty thoroughly, called db2qml. The tests are only high-level; they take a small database and confirms that the correct QuakeML is produced. As-written, db2qml is part of a package of software specific to the Geological Survey of Canada, one which has dependencies on other modules in that package. I could untangle it, but that's a fair amount of work. We use db2qml to pipe events out of Antelope and into the Canadian National Earthquake Database (whether one at a time or a day at a time).

Let me think on this. One option would be to revive event2qml and develop a simple high-level test for it. Another option would be to deprecate event2qml and instead disentangle db2qml from the the GSC packages. It wouldn't have the parameter file type configuration interface, but I haven't seen the benefit of that over the subset expressions I support in db2qml. The first option rocks the boat less, but doesn't appeal as much because I don't foresee us ever using event2qml.

Nick

**Comment by geoffdavis** [comment]
Nick, thanks. I'm going to go ahead and merge this pull request so that others can test it out.

**Pull request merged**
